apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-fe-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-fe
  template:
    metadata:
      labels:
        app: client-fe
    spec:
      containers:
        - name: client-fe
          image: prosenkiewicz/client-fe
          env:
            - name: REACT_APP_API_BASE_URL
              value: "http://mern-microservices.com/service/"
            - name: REACT_APP_MICROSERVICES_API_BASE_URL
              value: "http://mern-microservices.com/service/"

---
apiVersion: v1
kind: Service
metadata:
  name: client-fe-srv
spec:
  selector:
    app: client-fe
  ports:
    - name: client-fe
      protocol: TCP
      port: 3000
      targetPort: 3000
