apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: prosenkiewicz/auth
      context: auth
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: prosenkiewicz/admin
      context: admin
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: prosenkiewicz/lead
      context: lead
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: prosenkiewicz/product
      context: product
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: prosenkiewicz/client
      context: client
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: prosenkiewicz/client-fe
      context: client-fe
      sync:
        manual:
          - src: "**/*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: prosenkiewicz/monolith-be
      context: monolith-be
      sync:
        manual:
          - src: "**/*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl: {}
